{{- range .Values.issuers }}
{{- if and .acme .acme.privateKey }}
apiVersion: v1
kind: Secret
metadata: 
  name: extension-shoot-cert-service-issuer-{{ .name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  email: {{ .acme.email | b64enc | trim }}
  privateKey: {{ .acme.privateKey | b64enc | trim }}
{{- end }}
---
{{- if .ca }}
apiVersion: v1
kind: Secret
metadata:
  name: extension-shoot-cert-service-issuer-{{ .name }}-ca
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .ca.certificate | b64enc | trim }}
  tls.key: {{ .ca.certificateKey | b64enc | trim }}
{{- end }}
---
apiVersion: cert.gardener.cloud/v1alpha1
kind: Issuer
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
{{- if .acme }}
  acme:
    server: {{ .acme.server }}
    email: {{ .acme.email }}
    privateKeySecretRef:
{{- if .acme.privateKeySecretName }}
      name: {{ .acme.privateKeySecretName }}
{{- else }}
      name: extension-shoot-cert-service-issuer-{{ .name }}
{{- end }}
      namespace: {{ $.Release.Namespace }}
{{- if and (not .acme.privateKey) (not .acme.privateKeySecretName) }}
    autoRegistration: true
{{- end }}
{{- if .acme.externalAccountBinding }}
    externalAccountBinding:
      keyID: {{ .acme.externalAccountBinding.keyID }}
      keySecretRef:
        name: {{ .acme.externalAccountBinding.keySecretName }}
        namespace: {{ $.Release.Namespace }}
{{- end }}
{{- if .acme.skipDNSChallengeValidation }}
    skipDNSChallengeValidation: {{ .acme.skipDNSChallengeValidation }}
{{- end }}
{{- if .acme.domains }}
    domains:
{{- if .acme.domains.include }}
      include:
{{ toYaml .acme.domains.include | indent 6 }}
{{- end }}
{{- if .acme.domains.exclude }}
      exclude:
{{ toYaml .acme.domains.exclude | indent 6 }}
{{- end }}
{{- end }}
{{- if .precheckNameservers }}
    precheckNameservers:
  {{- range .precheckNameservers }}
    - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- if .ca }}
  ca:
    privateKeySecretRef:
      name: extension-shoot-cert-service-issuer-{{ .name }}-ca
      namespace: {{ $.Release.Namespace }}
{{- end }}
{{- if .requestsPerDayQuota }}
  requestsPerDayQuota: {{ .requestsPerDayQuota }}
{{- end }}
{{- end }}
