---
apiVersion: shoot-cert-service.extensions.config.gardener.cloud/v1alpha1
kind: Configuration
issuerName: gardener
restrictIssuer: true
acme:
# deactivateAuthorizations: true
  email: john.doe@example.com
  server: https://acme-v02.api.letsencrypt.org/directory
  propagationTimeout: 60s # TTL for DNS01 challenges
# privateKey: | # Optional key for Let's Encrypt account.
#   -----BEGIN BEGIN RSA PRIVATE KEY-----
#   ...
#   -----END RSA PRIVATE KEY-----
