---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: certificate-service
  namespace: shoot--foo--bar
spec:
  type: shoot-cert-service
  providerConfig:
    apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
    kind: CertConfig
    issuers:
    - name: custom
      server: https://acme-v02.api.letsencrypt.org/directory
      email: john.doe@example.com
      privateKeySecretName: custom-privatekey # referenced resource, the private key must be stored in the secret at `data.privateKey`
    - name: custom-eab
      server: https://acme.my-eab-ca-provider.com/v2/acme/directory/
      email: john.doe@example.com
      externalAccountBinding:
        keyID: aaaabbbbccccddddeee
        keySecretName: issuer-custom-eab-hmackey # referenced resource, the "MAC key" must be stored in the secret at `data.hmacKey`
      skipDNSChallengeValidation: true
      domains:
        include:
          - sub1.my-domain.com
          - sub2.my-domain.com
        exclude:
          - private.sub1.my-domain.com
    dnsChallengeOnShoot: # controls where the DNS entries for DNS01 challenges are created
      enabled: false
      # namespace: kube-system
      # dnsClass: foo
    #shootIssuers: # optionally overwrite global service configuration for issuers on shoot cluster
    #  enabled: false