apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
  name: extension-shoot-cert-service
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/releases/charts/gardener/extensions/shoot-cert-service:v1.51.0-dev
      injectGardenKubeconfig: true
      policy: Always
      runtimeClusterValues:
        certificateConfig:
          defaultIssuer:
            acme:
              email: some.user@example.com
              server: https://acme-v02.api.letsencrypt.org/directory
            name: garden
        gardenerCertificates:
          runtimeCluster:
            enabled: true
      values:
        certificateConfig:
          defaultIssuer:
            acme:
              email: some.user@example.com
              server: https://acme-v02.api.letsencrypt.org/directory
            name: garden
        gardenerCertificates:
          seed:
            dnsSecretRole: internal-domain
            enabled: true
  resources:
  - globallyEnabled: true
    kind: Extension
    type: shoot-cert-service
    workerlessSupported: true
