//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/gardener-extension-shoot-cert-service/pkg/apis/config"
	configv1alpha1 "github.com/gardener/gardener/extensions/pkg/apis/config/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ACME)(nil), (*config.ACME)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ACME_To_config_ACME(a.(*ACME), b.(*config.ACME), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ACME)(nil), (*ACME)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ACME_To_v1alpha1_ACME(a.(*config.ACME), b.(*ACME), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CA)(nil), (*config.CA)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CA_To_config_CA(a.(*CA), b.(*config.CA), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.CA)(nil), (*CA)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_CA_To_v1alpha1_CA(a.(*config.CA), b.(*CA), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Configuration)(nil), (*config.Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Configuration_To_config_Configuration(a.(*Configuration), b.(*config.Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Configuration)(nil), (*Configuration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Configuration_To_v1alpha1_Configuration(a.(*config.Configuration), b.(*Configuration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PrivateKeyDefaults)(nil), (*config.PrivateKeyDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PrivateKeyDefaults_To_config_PrivateKeyDefaults(a.(*PrivateKeyDefaults), b.(*config.PrivateKeyDefaults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.PrivateKeyDefaults)(nil), (*PrivateKeyDefaults)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_PrivateKeyDefaults_To_v1alpha1_PrivateKeyDefaults(a.(*config.PrivateKeyDefaults), b.(*PrivateKeyDefaults), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShootIssuers)(nil), (*config.ShootIssuers)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShootIssuers_To_config_ShootIssuers(a.(*ShootIssuers), b.(*config.ShootIssuers), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ShootIssuers)(nil), (*ShootIssuers)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ShootIssuers_To_v1alpha1_ShootIssuers(a.(*config.ShootIssuers), b.(*ShootIssuers), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ACME_To_config_ACME(in *ACME, out *config.ACME, s conversion.Scope) error {
	out.Email = in.Email
	out.Server = in.Server
	out.PrivateKey = (*string)(unsafe.Pointer(in.PrivateKey))
	out.PropagationTimeout = (*v1.Duration)(unsafe.Pointer(in.PropagationTimeout))
	out.PrecheckNameservers = (*string)(unsafe.Pointer(in.PrecheckNameservers))
	out.CACertificates = (*string)(unsafe.Pointer(in.CACertificates))
	out.DeactivateAuthorizations = (*bool)(unsafe.Pointer(in.DeactivateAuthorizations))
	return nil
}

// Convert_v1alpha1_ACME_To_config_ACME is an autogenerated conversion function.
func Convert_v1alpha1_ACME_To_config_ACME(in *ACME, out *config.ACME, s conversion.Scope) error {
	return autoConvert_v1alpha1_ACME_To_config_ACME(in, out, s)
}

func autoConvert_config_ACME_To_v1alpha1_ACME(in *config.ACME, out *ACME, s conversion.Scope) error {
	out.Email = in.Email
	out.Server = in.Server
	out.PrivateKey = (*string)(unsafe.Pointer(in.PrivateKey))
	out.PropagationTimeout = (*v1.Duration)(unsafe.Pointer(in.PropagationTimeout))
	out.PrecheckNameservers = (*string)(unsafe.Pointer(in.PrecheckNameservers))
	out.CACertificates = (*string)(unsafe.Pointer(in.CACertificates))
	out.DeactivateAuthorizations = (*bool)(unsafe.Pointer(in.DeactivateAuthorizations))
	return nil
}

// Convert_config_ACME_To_v1alpha1_ACME is an autogenerated conversion function.
func Convert_config_ACME_To_v1alpha1_ACME(in *config.ACME, out *ACME, s conversion.Scope) error {
	return autoConvert_config_ACME_To_v1alpha1_ACME(in, out, s)
}

func autoConvert_v1alpha1_CA_To_config_CA(in *CA, out *config.CA, s conversion.Scope) error {
	out.Certificate = in.Certificate
	out.CertificateKey = in.CertificateKey
	out.CACertificates = (*string)(unsafe.Pointer(in.CACertificates))
	return nil
}

// Convert_v1alpha1_CA_To_config_CA is an autogenerated conversion function.
func Convert_v1alpha1_CA_To_config_CA(in *CA, out *config.CA, s conversion.Scope) error {
	return autoConvert_v1alpha1_CA_To_config_CA(in, out, s)
}

func autoConvert_config_CA_To_v1alpha1_CA(in *config.CA, out *CA, s conversion.Scope) error {
	out.Certificate = in.Certificate
	out.CertificateKey = in.CertificateKey
	out.CACertificates = (*string)(unsafe.Pointer(in.CACertificates))
	return nil
}

// Convert_config_CA_To_v1alpha1_CA is an autogenerated conversion function.
func Convert_config_CA_To_v1alpha1_CA(in *config.CA, out *CA, s conversion.Scope) error {
	return autoConvert_config_CA_To_v1alpha1_CA(in, out, s)
}

func autoConvert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	out.IssuerName = in.IssuerName
	out.RestrictIssuer = (*bool)(unsafe.Pointer(in.RestrictIssuer))
	out.DefaultRequestsPerDayQuota = (*int32)(unsafe.Pointer(in.DefaultRequestsPerDayQuota))
	out.ShootIssuers = (*config.ShootIssuers)(unsafe.Pointer(in.ShootIssuers))
	out.ACME = (*config.ACME)(unsafe.Pointer(in.ACME))
	out.CA = (*config.CA)(unsafe.Pointer(in.CA))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	out.PrivateKeyDefaults = (*config.PrivateKeyDefaults)(unsafe.Pointer(in.PrivateKeyDefaults))
	return nil
}

// Convert_v1alpha1_Configuration_To_config_Configuration is an autogenerated conversion function.
func Convert_v1alpha1_Configuration_To_config_Configuration(in *Configuration, out *config.Configuration, s conversion.Scope) error {
	return autoConvert_v1alpha1_Configuration_To_config_Configuration(in, out, s)
}

func autoConvert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	out.IssuerName = in.IssuerName
	out.RestrictIssuer = (*bool)(unsafe.Pointer(in.RestrictIssuer))
	out.DefaultRequestsPerDayQuota = (*int32)(unsafe.Pointer(in.DefaultRequestsPerDayQuota))
	out.ShootIssuers = (*ShootIssuers)(unsafe.Pointer(in.ShootIssuers))
	out.ACME = (*ACME)(unsafe.Pointer(in.ACME))
	out.CA = (*CA)(unsafe.Pointer(in.CA))
	out.HealthCheckConfig = (*configv1alpha1.HealthCheckConfig)(unsafe.Pointer(in.HealthCheckConfig))
	out.PrivateKeyDefaults = (*PrivateKeyDefaults)(unsafe.Pointer(in.PrivateKeyDefaults))
	return nil
}

// Convert_config_Configuration_To_v1alpha1_Configuration is an autogenerated conversion function.
func Convert_config_Configuration_To_v1alpha1_Configuration(in *config.Configuration, out *Configuration, s conversion.Scope) error {
	return autoConvert_config_Configuration_To_v1alpha1_Configuration(in, out, s)
}

func autoConvert_v1alpha1_PrivateKeyDefaults_To_config_PrivateKeyDefaults(in *PrivateKeyDefaults, out *config.PrivateKeyDefaults, s conversion.Scope) error {
	out.Algorithm = (*string)(unsafe.Pointer(in.Algorithm))
	out.SizeRSA = (*int)(unsafe.Pointer(in.SizeRSA))
	out.SizeECDSA = (*int)(unsafe.Pointer(in.SizeECDSA))
	return nil
}

// Convert_v1alpha1_PrivateKeyDefaults_To_config_PrivateKeyDefaults is an autogenerated conversion function.
func Convert_v1alpha1_PrivateKeyDefaults_To_config_PrivateKeyDefaults(in *PrivateKeyDefaults, out *config.PrivateKeyDefaults, s conversion.Scope) error {
	return autoConvert_v1alpha1_PrivateKeyDefaults_To_config_PrivateKeyDefaults(in, out, s)
}

func autoConvert_config_PrivateKeyDefaults_To_v1alpha1_PrivateKeyDefaults(in *config.PrivateKeyDefaults, out *PrivateKeyDefaults, s conversion.Scope) error {
	out.Algorithm = (*string)(unsafe.Pointer(in.Algorithm))
	out.SizeRSA = (*int)(unsafe.Pointer(in.SizeRSA))
	out.SizeECDSA = (*int)(unsafe.Pointer(in.SizeECDSA))
	return nil
}

// Convert_config_PrivateKeyDefaults_To_v1alpha1_PrivateKeyDefaults is an autogenerated conversion function.
func Convert_config_PrivateKeyDefaults_To_v1alpha1_PrivateKeyDefaults(in *config.PrivateKeyDefaults, out *PrivateKeyDefaults, s conversion.Scope) error {
	return autoConvert_config_PrivateKeyDefaults_To_v1alpha1_PrivateKeyDefaults(in, out, s)
}

func autoConvert_v1alpha1_ShootIssuers_To_config_ShootIssuers(in *ShootIssuers, out *config.ShootIssuers, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_ShootIssuers_To_config_ShootIssuers is an autogenerated conversion function.
func Convert_v1alpha1_ShootIssuers_To_config_ShootIssuers(in *ShootIssuers, out *config.ShootIssuers, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShootIssuers_To_config_ShootIssuers(in, out, s)
}

func autoConvert_config_ShootIssuers_To_v1alpha1_ShootIssuers(in *config.ShootIssuers, out *ShootIssuers, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_config_ShootIssuers_To_v1alpha1_ShootIssuers is an autogenerated conversion function.
func Convert_config_ShootIssuers_To_v1alpha1_ShootIssuers(in *config.ShootIssuers, out *ShootIssuers, s conversion.Scope) error {
	return autoConvert_config_ShootIssuers_To_v1alpha1_ShootIssuers(in, out, s)
}
