version: "2"
run:
  concurrency: 4
linters:
  disable:
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: 'ST1001:' # should not use dot imports
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - zz_generated\..*\.go$
formatters:
  exclusions:
    generated: lax
    paths:
      - zz_generated\..*\.go$