---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issuers.cert.gardener.cloud
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-cert-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.acme.server
      description: ACME Server
      name: SERVER
      type: string
    - JSONPath: .spec.acme.email
      description: ACME Registration email
      name: EMAIL
      type: string
    - JSONPath: .status.state
      description: Status of registration
      name: STATUS
      type: string
    - JSONPath: .status.type
      description: Issuer type
      name: TYPE
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: AGE
      type: date
  conversion:
    strategy: None
  group: cert.gardener.cloud
  names:
    kind: Issuer
    listKind: IssuerList
    plural: issuers
    shortNames:
      - issuer
    singular: issuer
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
