apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gardener-extension-shoot-cert-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-shoot-cert-service
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-shoot-cert-service
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.GitVersion }}
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
