{{- if .Values.gep19Monitoring }}
{{- if gt .Values.configuration.certExpirationAlertDays 0.0 }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: shoot-cert-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    prometheus: shoot
spec:
  groups:
  - name: cert-controller-manager.rules
    rules:
    - alert: SslCertificateWillExpireSoon
      expr: ((cert_management_cert_object_expire > 0) - time()) / 86400 <= {{ .Values.configuration.certExpirationAlertDays }}
      for: 30m
      labels:
        service: cert-controller-manager
        severity: critical
        type: seed
        visibility: operator
      annotations:
        description: Certificate in namespace {{ .Release.Namespace }} will expire in less than {{ .Values.configuration.certExpirationAlertDays }} days.
        summary: TLS certificate will expire in less than {{ .Values.configuration.certExpirationAlertDays }} days
{{- end }}
{{- end }}
