{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "cert-management.fullname" . }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cert-management.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledValues: RequestsOnly
        minAllowed:
          memory: {{ .Values.vpa.minAllowed.memory }}
{{- end }}
