#!/usr/bin/env bash

COMPONENT_PREFIXES="eu.gcr.io/gardener-project/cert-controller-manager" \
  "$(dirname $0)"/../vendor/github.com/gardener/gardener/hack/.ci/component_descriptor "$(dirname $0)"/..
