{
 "title": "Cert Controller Manager",
 "tags": [
  "controlplane",
  "seed",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "severity", "label": "Severity", "query": "INFO,WARN,ERR,DBG,NOTICE,FATAL" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "UP Time",
   "type": "singlestat",
   "description": "Current uptime status.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"cert-controller-manager\"} == 1) / sum(up{job=\"cert-controller-manager\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage and shows the requests and limits.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"cert-controller-manager-(.+)\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"cert-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"cert-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"cert-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"cert-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"cert-controller-manager-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Certificate Objects",
   "type": "graph",
   "description": "Certificate resource objects per issuer",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cert_management_cert_entries) by (pod, issuer)",
     "legendFormat": "issuer={{issuer}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Certificate Secrets",
   "type": "graph",
   "description": "Number of certificate secrets per classification (only updated on startup and every 24h on GC of secrets). Currently there are three classifications: `total` = total number of certificate secrets on the source cluster, `revoked` = number of revoked certificate secrets, `backup`= number of backups of certificate secrets (every certificate has a backup secret in the `kube-system` namespace to allow revocation even if it is not used anymore)",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cert_management_secrets) by (classification)",
     "legendFormat": "{{classification}}"
    }
   ]
  },
  {
   "title": "Certificate Objects with Overdue Renewal",
   "type": "stat",
   "description": "Number of certificate objects with certificate's renewal overdue",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cert_management_overdue_renewal_certificates"
    }
   ]
  },
  {
   "title": "Expire dates of certficaate objects",
   "type": "bargauge",
   "description": "Shows the expiration dates of the certificates objects in days. Normally a certificate should be renewed 30 days before its expires.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cert_management_cert_object_expire-time())/86400",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "ACME Account Registrations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cert_management_acme_account_registrations) by (uri, email)",
     "legendFormat": "email={{email}}, uri={{uri}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{pod_name=~\"cert-controller-manager-(.+)\", severity=~\"$severity\"} |~ \"$search\""
    }
   ]
  }
 ]
}