name: Prepare Release

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: '1.24'
    - name: make-generate
      shell: bash
      run: |
        set -eu
        make generate
